# Generated by Django 6.1.1 on 2026-10-03 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_venta_producto_costo_detalleventa'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='codigo_barras',
            field=models.CharField(blank=True, help_text='Se lee con el lector del kiosco. No puede repetirse.', max_length=50, null=True, unique=True, verbose_name='Código de barras'),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_minimo',
            field=models.PositiveIntegerField(default=5, help_text='Alerta de stock bajo (HU-06): se marca cuando el stock actual es menor o igual a este valor.'),
        ),
    ]
