# Generated by Django 6.1.1 on 2026-10-05 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_producto_codigo_barras_producto_stock_minimo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta')], default='efectivo', max_length=10, verbose_name='Método de pago'),
        ),
        migrations.AddField(
            model_name='venta',
            name='monto_entregado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Solo para pagos en efectivo.', max_digits=10, null=True, verbose_name='Monto entregado'),
        ),
        migrations.AddField(
            model_name='venta',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Cajero responsable'),
        ),
        migrations.AddField(
            model_name='venta',
            name='vuelto',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto entregado menos el total. Solo para efectivo.', max_digits=10, null=True),
        ),
    ]
